In [17]:
import numpy as np
#Numpy first task
A=np.array([[3,5,7,9],
  [6,7,9,0]])
print (A)
print(A.size)
print('The Transpose of matrix A is',a.T  )
B=np.array([[5,7,3,1],
    [6,0,1,3]])
print('The summation of Aand B matrix is',A+B)



[[3 5 7 9]
 [6 7 9 0]]
8
The Transpose of matrix A is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
The summation of Aand B matrix is [[ 8 12 10 10]
 [12  7 10  3]]


In [18]:
import numpy as np
a=np.arange(0,18)
b=np.arange(20,38)
c=a.reshape(6,3)
d=b.reshape(6,3)
print (c)
print(d)
print ('The suummation is',c+d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]
The suummation is [[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
